### ISSUE TITLE
A separate library should be used instead of near-sdk-as

### ISSUE THREAD

**Issue by yjhmelody** [gagdiez/encoder-as#3]

**Comment by willemneal** [comment]
It's not being used.  So it should be removed.

**Comment by ashutoshvarma** [comment]
Only, `base64` and `u128` are being used from `near-sdk-as`, which can be replaced with `as-bignum` and `as-base64`

**Comment by gagdiez** [comment]
Indeed, we fixed the encoding-decoding for u128 yesterday, and I will update the dependencies today

**Comment by ashutoshvarma** [comment]
> Indeed, we fixed the encoding-decoding for u128 yesterday, and I will update the dependencies today

I made a PR for that already :)

**Comment by gagdiez** [comment]
Merged #8
