### ISSUE TITLE
Should each encoding method return a value to indicate the result of the operation?

### ISSUE THREAD

**Issue by yjhmelody** [gagdiez/encoder-as#5]

**Comment by gagdiez** [comment]
encoder-as will be used mainly to allow smart contracts in the NEAR blockchain to communicate. In such cases, I prefer the developers of encoder/decoder to expend more time in testing, than the users to expend time in computing (and expending GAS). Therefore, I am designing encoder-as such that it is computationally efficient, so I prefer to have a "try and fail/return garbage" approach to encoding/decoding.
