### ISSUE TITLE
Should all types in the standard library be supported?

### ISSUE THREAD

**Issue by yjhmelody** [gagdiez/encoder-as#6]
Include Error/ArrayBuffer/DataView/XXXArray (ignoring Symbol)

**Comment by willemneal** [comment]
Except for error the other types should work since they are `ArrayLike`.  But I do think that it makes since to specialize ArrayBuffer.  Then for the extra types `Error`, etc, making sure they are transformed should make it work.

**Comment by gagdiez** [comment]
I agree with @willemneal. I propose to make a first stable release handling everything through ArrayLike, and then specialize ArrayBuffer.
